### ISSUE TITLE
Styled Markup Feedback!

### ISSUE THREAD

**Issue by rijkvanzanten** [vee-mai/Manuscript#2]
- [ ] An HTML document can only have one `h1`. [Use a single `h1` with nested `span` elements here instead](https://github.com/vee-mai/Manuscript/blob/41c2148c6938578006121ad14e0a6e8620c0d418/index.html#L15-L20)
- [x] [Two closing `</span>` for one open tag](https://github.com/vee-mai/Manuscript/blob/41c2148c6938578006121ad14e0a6e8620c0d418/index.html#L29)
- [x] There's a [dedicated selector](https://developer.mozilla.org/en-US/docs/Web/CSS/::first-letter) for the first letter of a sentence. Easier than another [span with a class](https://github.com/vee-mai/Manuscript/blob/41c2148c6938578006121ad14e0a6e8620c0d418/index.html#L29)
- [x] [Closing tags don't have attributes](https://github.com/vee-mai/Manuscript/blob/41c2148c6938578006121ad14e0a6e8620c0d418/index.html#L34)
- [x] Once you find yourself adding incremental classes (like `P4` `P6` etc), you're probably better off with the [`:nth-child` selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child)
- [ ] Try to use more descriptive class names. `H` and `OO` don't really mean anything in context. I'd personally use an ID on the parent like `#title-art` and then style the individual letters with nth-childs, like `#title-art > :nth-child(2) { ... }`
- [ ] Noticing quite a lot of repeated code like font-family, size, weight etc. Similar to the previous point, you can simplify that by doing something like:
  
  ```css
  #title-art {
    font-family: 'Montserrat', sans-serif;
    font-size: 90px;
    font-weight: bolder;
  }

  #title-art > :nth-child(1) {
    transform: rotate(); /* etc */
  }
  ```

Overall output looks pretty solid! Keeping the design simple helps you focus on getting the details right.
